export default {
  CREATE_GROUP: 'CREATE_GROUP',
  SELECT_GROUP: 'SELECT_GROUP',
  SELECT_USERS: 'SELECT_USERS',
  ADD_USERS_TO_GROUP: 'ADD_USERS_TO_GROUP',
  REMOVE_USER_FROM_GROUP: 'REMOVE_USER_FROM_GROUP',
  CHANGE_USER_GROUP: 'CHANGE_USER_GROUP',
  REORDER_USERS: 'REORDER_USERS',
  REORDER_UP: 'REORDER_UP',
  REORDER_DOWN: 'REORDER_DOWN',
};