export default {
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN:    'USER_LOGIN',
  USER_LOGOUT:   'USER_LOGOUT',
  USER_NEXT_STEP: 'USER_NEXT_STEP',
  USER_BACK_STEP: 'USER_BACK_STEP',
  USER_CAMERA_ROTATE: 'USER_CAMERA_ROTATE',
}